# Generated by Django 3.2 on 2021-05-07 14:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fname', models.CharField(max_length=100)),
                ('lname', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('male', 'male'), ('female', 'female')], default='male', max_length=15)),
                ('birth_date', models.DateField()),
                ('email', models.EmailField(max_length=120, unique=True)),
                ('contact_no', models.CharField(max_length=15)),
                ('avatar', models.ImageField(upload_to='avatar/')),
                ('status', models.CharField(choices=[('pending', 'pending'), ('approve', 'approve')], default='pending', max_length=20)),
                ('online', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=True)),
                ('password', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=150)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('driverId', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('liscence_no', models.CharField(max_length=20, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fname', models.CharField(max_length=100)),
                ('lname', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('male', 'male'), ('female', 'female')], default='male', max_length=15)),
                ('birth_date', models.DateField()),
                ('email', models.EmailField(max_length=120, unique=True)),
                ('contact_no', models.CharField(max_length=15)),
                ('avatar', models.ImageField(upload_to='avatar/')),
                ('status', models.CharField(choices=[('pending', 'pending'), ('approve', 'approve')], default='pending', max_length=20)),
                ('online', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=True)),
                ('password', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=150)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('staffId', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('admin', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StaffNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notification', models.TextField()),
                ('watch', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='VehicleService',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('serviceId', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='vehicle_thumbnail/')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Mechanic',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fname', models.CharField(max_length=100)),
                ('lname', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('male', 'male'), ('female', 'female')], default='male', max_length=15)),
                ('birth_date', models.DateField()),
                ('email', models.EmailField(max_length=120, unique=True)),
                ('contact_no', models.CharField(max_length=15)),
                ('avatar', models.ImageField(upload_to='avatar/')),
                ('status', models.CharField(choices=[('pending', 'pending'), ('approve', 'approve')], default='pending', max_length=20)),
                ('online', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=True)),
                ('password', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=150)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('mechanicId', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('pan_no', models.CharField(max_length=20, unique=True)),
                ('services', models.ManyToManyField(related_name='provide_services', to='tracker.VehicleService')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Help',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cur_lat', models.FloatField()),
                ('cur_lon', models.FloatField()),
                ('problem_desc', models.TextField()),
                ('vehicle_image', models.ImageField(upload_to='vehicle_image/')),
                ('accept', models.BooleanField(default=False)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.driver')),
                ('mechanic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.mechanic')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.vehicleservice')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
